name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Download SDK
        run: npx -p @arkts/sdk-downloader arkcode-sdk-downloader download --api-version API18 --target-dir /opt/sdk --arch X86 --os Linux
      
      - name: Set SDK permissions
        run: |
          sudo chmod -R +x /opt/sdk/native/llvm/bin/
          ls -la /opt/sdk/native/llvm/bin/

      - name: Verify SDK installation
        run: |
          echo "Checking SDK files:"
          ls -la /opt/sdk/native/llvm/bin/clang
          /opt/sdk/native/llvm/bin/clang --version
          
      - name: Set up environment
        run: |
          echo "CC=/opt/sdk/native/llvm/bin/clang" >> $GITHUB_ENV
          echo "CXX=/opt/sdk/native/llvm/bin/clang++" >> $GITHUB_ENV
          echo "LD=/opt/sdk/native/llvm/bin/lld" >> $GITHUB_ENV
          echo "STRIP=/opt/sdk/native/llvm/bin/llvm-strip" >> $GITHUB_ENV
          echo "RANLIB=/opt/sdk/native/llvm/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "OBJDUMP=/opt/sdk/native/llvm/bin/llvm-objdump" >> $GITHUB_ENV
          echo "AR=/opt/sdk/native/llvm/bin/llvm-ar" >> $GITHUB_ENV
          echo "NM=/opt/sdk/native/llvm/bin/llvm-nm" >> $GITHUB_ENV
          echo "OBJCOPY=/opt/sdk/native/llvm/bin/llvm-objcopy" >> $GITHUB_ENV
          echo "CFLAGS=-fPIC -D__MUSL__=1" >> $GITHUB_ENV
          echo "CXXFLAGS=-fPIC -D__MUSL__=1" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3 python3-pip
      
      - name: Build project
        run: |
          npm install --verbose --build-from-source --runtime=electron --arch=x64 --target=20.18.1 --dist-url=https://electronjs.org/headers
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/Release/*.so
            build/Release/*.node
            build/Debug/*.so
            build/Debug/*.node
