name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install sdk
        run: npm install -g @arkts/sdk-downloader

      - name: Download SDK
        run: npx -p @arkts/sdk-downloader arkcode-sdk-downloader download --api-version API18 --output /opt/sdk --arch X86 --os Linux

      - name: Set up environment
        run: |
          echo "SDK_PATH=/opt/sdk" >> $GITHUB_ENV
          echo "CC=${SDK_PATH}/16/native/llvm/bin/clang" >> $GITHUB_ENV
          echo "CXX=${SDK_PATH}/16/native/llvm/bin/clang++" >> $GITHUB_ENV
          echo "LD=${SDK_PATH}/16/native/llvm/bin/lld" >> $GITHUB_ENV
          echo "STRIP=${SDK_PATH}/16/native/llvm/bin/llvm-strip" >> $GITHUB_ENV
          echo "RANLIB=${SDK_PATH}/16/native/llvm/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "OBJDUMP=${SDK_PATH}/16/native/llvm/bin/llvm-objdump" >> $GITHUB_ENV
          echo "AR=${SDK_PATH}/16/native/llvm/bin/llvm-ar" >> $GITHUB_ENV
          echo "NM=${SDK_PATH}/16/native/llvm/bin/llvm-nm" >> $GITHUB_ENV
          echo "OBJCOPY=${SDK_PATH}/16/native/llvm/bin/llvm-objcopy" >> $GITHUB_ENV
          echo "CFLAGS=-fPIC -D__MUSL__=1" >> $GITHUB_ENV
          echo "CXXFLAGS=-fPIC -D__MUSL__=1" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3 python3-pip
      
      - name: Build project
        run: |
          npm install --verbose --build-from-source --runtime=electron --arch=x64 --target=20.18.1 --dist-url=https://electronjs.org/headers
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/Release/*.so
            build/Release/*.node
            build/Debug/*.so
            build/Debug/*.node
